import { useInView } from "react-intersection-observer"
import { FeaturedCard } from "./FeaturedCard/FeaturedCard"
import { ViewProjectsButton } from "./ViewProjectsButton"



const style = {
    height: "100%",
    width: "100vw"
}

const featuredProjects = [
  {
    id: 1,
    title: "Bill Management System",
    subtitle: "SMS integration for customers included",
    stack: [
      "React JS",
      "Spring Boot",
      "MySql",
      "Twilio"
    ],
    demoUrl: "https://alcantarawater.online",
    ghUrl: "",
    images: [
      "https://i.imgur.com/ORBLmbp.jpg",
      "https://i.imgur.com/3jVsKH1.jpg",
      "https://i.imgur.com/SK1vOgr.jpg",
      "https://i.imgur.com/9tzjmhV.jpg"
    ],
    displayImg: "https://i.imgur.com/5ywGeRN.jpg",
    description: [
      "This is a simple app whose goal is to manage the water bills of a small community. Customers can view their accounts while admins can view, register, and delete accounts.",
      "Monthly billing statements can be generated by providing the system the latest meter reading of each account, and the rest will be taken care of.",
      "Registered customers will receive their monthly water bill via SMS, through the integration with Twilio."
    ],
    shortDescription: "This is a simple app whose goal is to manage the water bills of a small community. Login is available for both admin side and customer side. Registered customers will be notified about their new monthly billing statements through SMS."
  },
  {
    id: 2,
    title: "Simple Chat App",
    subtitle: "Try it out with your buddy",
    stack: [
      "React JS",
      "Spring Boot",
      "Spring WebSockets"
    ],
    demoUrl: "https://edamor.github.io/simple-chat-react-1",
    ghUrl: "https://github.com/edamor/simple-chat-react-1",
    images: [
      "https://i.imgur.com/K5qQDKa.jpg",
      "https://i.imgur.com/ILvjzt5.jpg",
      "https://i.imgur.com/QYRXSMT.jpg"
    ],
    displayImg: "https://i.imgur.com/nnzG4j7.jpg",
    description: [
      "This is a real-time public chat app built with React JS and Spring WebSockets. All messages are being sent in real-time to all active subscribers.",
      "The connection happens when a user opens the app. The app then communicates with the server through STOMP over WebSocket protocol.",
      "Try it out with your buddy!",
      "This project is being hosted at Heroku and Github Pages."
    ],
    shortDescription: "This is a real-time public chat app built with React JS and Spring WebSockets. All messages are being sent in real-time to all active subscribers."
  }
]



export const FeaturedProjects = (props) => {

  
  const [ref, inView] = useInView();

  return (
    <div className="featured-projects" style={style} ref={ref} >
      <div 
        className={`waypoint ${inView ? "animated slide-in-left" : ""}`}
        style={{ animationDelay: "0.12s"}}
      >
        <FeaturedCard alt={false} project={featuredProjects[0]} />
      </div>
      <div 
        className={`waypoint ${inView ? "animated slide-in-right" : ""}`}
        style={{ animationDelay: "0.36s"}}
      >
        <FeaturedCard alt={true} project={featuredProjects[1]} />
      </div>
      <div 
        className={`waypoint ${inView ? "animated pop-in" : ""}`}
        style={{ animationDelay: "0.52s"}}
      >
        <ViewProjectsButton />
      </div>
    </div>
  )
}